import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-300 px-4 py-16">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="text-xs text-neutral-500 hover:text-orange-300 transition-colors">
          &larr; Back to home
        </Link>

        <h1 className="text-2xl font-bold text-white mt-6 mb-8">Terms of Service</h1>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-white mb-2">1. Service Description</h2>
            <p>
              Poster Maker is an AI-powered poster generation service. Users can create poster designs
              using artificial intelligence by providing text prompts, style preferences, and other creative inputs.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">2. Credits and Payments</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>New accounts receive 2 free credits upon registration.</li>
              <li>Each poster generation consumes 1 credit per image variation.</li>
              <li>Credits are deducted at the time of generation and are <strong className="text-white">non-refundable</strong>, including in cases where generation fails due to content policy violations or prompt errors.</li>
              <li>Additional credits can be purchased through our pricing page. All purchases are final.</li>
              <li>Credits do not expire but are non-transferable.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">3. Acceptable Use</h2>
            <p>You agree not to use the service to generate content that is:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Illegal, harmful, or promotes violence</li>
              <li>Sexually explicit or pornographic</li>
              <li>Discriminatory or hateful toward any group</li>
              <li>Infringing on copyrights, trademarks, or intellectual property rights</li>
              <li>Deceptive, fraudulent, or misleading</li>
            </ul>
            <p className="mt-2">
              Violations may result in account suspension without credit refund.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">4. AI-Generated Content</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Images are generated by third-party AI models (OpenAI). Results may vary and are not guaranteed.</li>
              <li>You receive a non-exclusive license to use generated images for personal or commercial purposes.</li>
              <li>We do not claim ownership over your generated content.</li>
              <li>AI outputs may occasionally be inaccurate, unexpected, or fail to generate. Credits are consumed regardless of outcome.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">5. Account</h2>
            <p>
              You are responsible for maintaining the security of your account. We authenticate via Google OAuth
              and do not store passwords. You may request account deletion by contacting us.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">6. Limitation of Liability</h2>
            <p>
              The service is provided &quot;as is&quot; without warranties of any kind. We are not liable for any
              damages arising from the use of the service, including but not limited to failed generations,
              service interruptions, or loss of credits.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">7. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <p className="text-neutral-500 pt-4 border-t border-neutral-800">
            Last updated: February 2026
          </p>
        </div>
      </div>
    </div>
  );
}
